CREATE DATABASE ENDERECO

CREATE TABLE TBL_ENDERECO(
			endereco_id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
			cep INT NOT NULL,
			rua VARCHAR(100) NOT NULL,
			numero INT NOT NULL,
			cidade VARCHAR(60) NOT NULL,
			estado VARCHAR(20) NOT NULL,
			bairro VARCHAR(60) DEFAULT(''),
			complemento VARCHAR (20) DEFAULT('') )


INSERT INTO ENDERECO VALUES (06333450, 'RUA TRALÁLÁ',41, 'CARAPICUÍBA','SÃO PAULO', 'PQ JANDAIA','CASA')
INSERT INTO ENDERECO VALUES (06333500, 'RUA BIRU-BIRU-BIRU',500, 'MINAS NOVAS','MINAS GERAIS', 'MINAS NOVAS','MANSÃO')

